// This file is generated by npm run build:icons

export type IconName =
	| 'add-selected'
	| 'add'
	| 'bands-selected'
	| 'bands'
	| 'home-selected'
	| 'home'
	| 'remove-selected'
	| 'remove'
	| 'smile'
	| 'songs-selected'
	| 'songs'
	| 'students-selected'
	| 'students'
	| 'teachers-selected'
	| 'teachers'
