// This file is generated by npm run build:icons

export type IconName =
	| 'add-selected'
	| 'add'
	| 'bands-selected'
	| 'bands'
	| 'home-selected'
	| 'home'
	| 'student-selected'
	| 'student'
	| 'teacher-selected'
	| 'teacher'
